apiVersion: apps/v1
kind: Deployment
metadata:   
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  name: python-qcmfougw
spec:
  replicas: 1 
  template: 
    spec:
      containers:
      - image: quay.io/rhtap_qe/python-qcmfougw:327b0d169abf90822078fb7b25ecd90f1a906196@sha256:61e6be90bc5ee295e73b20effbd9cda01b61f1ab682264d6c9359306cc0eda1f
        name: container-image  
